In [1]:
import numpy as np

In [2]:
my_list = [1, 2, "test"]

In [3]:
my_list.append(7)

In [4]:
my_list

[1, 2, 'test', 7]

In [5]:
# 배열 : 파이썬 X
# 모듈사용으로 배열을 생성 > numpy
ar = np.array([1, 2, 4, 0, 7])

In [6]:
ar

array([1, 2, 4, 0, 7])

In [7]:
print(type(my_list))
print(type(ar))

<class 'list'>
<class 'numpy.ndarray'>


In [8]:
ar2 = np.array([1, 2, 4, 0, 7, "test"])

In [9]:
ar2

array(['1', '2', '4', '0', '7', 'test'], dtype='<U11')

In [11]:
list = [1, 2, 3]
arr = np.array([1, 2, 3])

In [13]:
list * 2

[1, 2, 3, 1, 2, 3]

In [14]:
arr + 2

array([3, 4, 5])

In [15]:
arr * 2

array([2, 4, 6])

In [16]:
list2 = []
for i in list:
    list2.append(i + 2)
list2

[3, 4, 5]

In [17]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

In [18]:
a + b

array([11, 22, 33])

In [19]:
a - b

array([ -9, -18, -27])

In [20]:
a / b

array([0.1, 0.1, 0.1])

In [21]:
a * b

array([10, 40, 90])

In [22]:
a

array([1, 2, 3])

In [23]:
a == 1

array([ True, False, False])

In [29]:
c = np.array([[0, 1, 2], [3, 4, 5], [3, 4, 5]])  # 2 x 3 array
c

array([[0, 1, 2],
       [3, 4, 5],
       [3, 4, 5]])

In [30]:
len(c)

3

In [31]:
c.ndim

2

In [33]:
a = np.array([1, 2, 3])
print(a.ndim)
print(a.shape)

1
(3,)


In [38]:
x = np.array([1, 2, "3.0"])
x.dtype

dtype('<U11')

In [39]:
x = np.array([1, 2, 3], dtype='f')
x.dtype

dtype('float32')

In [41]:
x

array([1., 2., 3.], dtype=float32)

In [42]:
np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([  0.,  inf, -inf,  nan])

In [43]:
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [44]:
b = np.zeros((2, 3))
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [45]:
c = np.zeros((5, 2), dtype="i")
c

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int32)

In [46]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
for i in np.arange(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [49]:
np.linspace(0, 100, 10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [50]:
A = np.array([[1, 2, 3], [4, 5, 6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [53]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [54]:
a  = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [58]:
a.reshape(2, 6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [59]:
a.reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [61]:
c = np.array([[1, 4], [2, 5], [3, 6]])
c

array([[1, 4],
       [2, 5],
       [3, 6]])

In [62]:
c.flatten()

array([1, 4, 2, 5, 3, 6])

In [63]:
a1 = np.ones((2, 3))
a1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [64]:
a2 = np.zeros((2, 2))
a2

array([[0., 0.],
       [0., 0.]])

In [66]:
np.vstack([a1, a2])

ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [67]:
a1t = a1.T

In [68]:
a1t

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [69]:
np.vstack([a1t, a2])

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [0., 0.],
       [0., 0.]])

In [70]:
x = np.array([1, 2, 3])

In [71]:
x

array([1, 2, 3])

In [73]:
x * 3

array([3, 6, 9])

In [74]:
a = np.array([[4,  3,  5,  7],
              [1, 12, 11,  9],
              [2, 15,  1, 14]])
a

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2, 15,  1, 14]])

In [80]:
np.sort(a, axis = 0)

array([[ 1,  3,  1,  7],
       [ 2, 12,  5,  9],
       [ 4, 15, 11, 14]])

In [81]:
import pandas as pd
data = {
    "2015": [9904312, 3448737, 2890451, 2466052],
    "2010": [9631482, 3393191, 2632035, 2431774],
    "2005": [9762546, 3512547, 2517680, 2456016],
    "2000": [9853972, 3655437, 2466338, 2473990],
    "지역": ["수도권", "경상권", "수도권", "경상권"],
    "2010-2015 증가율": [0.0283, 0.0163, 0.0982, 0.0141]
}
columns = ["지역", "2015", "2010", "2005", "2000", "2010-2015 증가율"]
index = ["서울", "부산", "인천", "대구"]
df = pd.DataFrame(data, index=index, columns=columns)
df

지역     2015     2010     2005     2000  2010-2015 증가율
서울  수도권  9904312  9631482  9762546  9853972         0.0283
부산  경상권  3448737  3393191  3512547  3655437         0.0163
인천  수도권  2890451  2632035  2517680  2466338         0.0982
대구  경상권  2466052  2431774  2456016  2473990         0.0141

In [84]:
df.describe()

2015          2010          2005          2000  2010-2015 증가율
count  4.000000e+00  4.000000e+00  4.000000e+00  4.000000e+00       4.000000
mean   4.677388e+06  4.522120e+06  4.562197e+06  4.612434e+06       0.039225
std    3.507776e+06  3.431328e+06  3.500545e+06  3.538749e+06       0.039809
min    2.466052e+06  2.431774e+06  2.456016e+06  2.466338e+06       0.014100
25%    2.784351e+06  2.581970e+06  2.502264e+06  2.472077e+06       0.015750
50%    3.169594e+06  3.012613e+06  3.015114e+06  3.064714e+06       0.022300
75%    5.062631e+06  4.952764e+06  5.075047e+06  5.205071e+06       0.045775
max    9.904312e+06  9.631482e+06  9.762546e+06  9.853972e+06       0.098200

In [85]:
x = np.array([18,   5,  10,  23,  19,  -8,  10,   0,   0,   5,   2,  15,   8,
              2,   5,   4,  15,  -1,   4,  -7, -24,   7,   9,  -6,  23, -13])

In [86]:
x

array([ 18,   5,  10,  23,  19,  -8,  10,   0,   0,   5,   2,  15,   8,
         2,   5,   4,  15,  -1,   4,  -7, -24,   7,   9,  -6,  23, -13])

In [87]:
len(x)

26

In [88]:
np.mean(x)

4.8076923076923075

In [89]:
np.var(x)

115.23224852071006

In [90]:
np.std(x)

10.734628476137871

In [91]:
np.max(x)

23

In [92]:
np.min(x)

-24

In [93]:
np.median(x)

5.0

In [94]:
np.percentile(x, 25) # 1 사분위수

-24.0

In [95]:
np.percentile(x, 50) # 2 사분위수

5.0

In [96]:
np.percentile(x, 75) # 3 사분위수

10.0

In [97]:
np.percentile(x, 100)  # 최댓값

23.0

In [98]:
from scipy.stats import describe
describe(x)

DescribeResult(nobs=26, minmax=(-24, 23), mean=4.8076923076923075, variance=119.84153846153846, skewness=-0.4762339485461929, kurtosis=0.37443381660038977)

In [102]:
df.describe()

2015          2010          2005          2000  2010-2015 증가율
count  4.000000e+00  4.000000e+00  4.000000e+00  4.000000e+00       4.000000
mean   4.677388e+06  4.522120e+06  4.562197e+06  4.612434e+06       0.039225
std    3.507776e+06  3.431328e+06  3.500545e+06  3.538749e+06       0.039809
min    2.466052e+06  2.431774e+06  2.456016e+06  2.466338e+06       0.014100
25%    2.784351e+06  2.581970e+06  2.502264e+06  2.472077e+06       0.015750
50%    3.169594e+06  3.012613e+06  3.015114e+06  3.064714e+06       0.022300
75%    5.062631e+06  4.952764e+06  5.075047e+06  5.205071e+06       0.045775
max    9.904312e+06  9.631482e+06  9.762546e+06  9.853972e+06       0.098200

In [114]:
np.random.seed(7777)
np.random.rand(5) # rand 0 ~ 1

array([0.81150513, 0.69232414, 0.45248612, 0.99662967, 0.98757038])

In [119]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [120]:
np.random.shuffle(x)
x

array([1, 5, 7, 4, 8, 6, 9, 3, 0, 2])

In [122]:
lotto = np.arange(1, 46)
lotto

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45])

In [126]:
np.random.shuffle(lotto)
lotto[:6]

array([33, 23, 10,  1, 45, 29])

In [127]:
lotto

array([33, 23, 10,  1, 45, 29, 25, 11, 40, 39, 36, 14,  4, 43, 38,  8, 31,
       21, 30, 17, 12, 16, 41,  6,  7, 28, 13,  2, 26,  9, 24, 15, 22, 27,
       20, 18, 44, 37, 32,  3, 42,  5, 35, 34, 19])

In [133]:
np.random.choice(lotto, 6, replace = True)

array([12, 42, 22, 22, 31,  3])

In [134]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [135]:
np.random.choice(x, 10, replace = True)

array([3, 4, 4, 0, 0, 4, 1, 4, 3, 2])

In [136]:
from scipy.stats import describe

a = np.random.rand(100)
b = np.random.randn(100)

In [137]:
a

array([0.91450684, 0.05088194, 0.04813755, 0.79276569, 0.03049997,
       0.05795778, 0.25187263, 0.64002052, 0.72660077, 0.40115089,
       0.64273993, 0.40686224, 0.63737159, 0.58279885, 0.15449673,
       0.73961686, 0.05734105, 0.68965081, 0.96296379, 0.18853921,
       0.02075053, 0.17589697, 0.51507408, 0.02939726, 0.26560385,
       0.79224262, 0.57908455, 0.07074794, 0.0123179 , 0.6210162 ,
       0.23142238, 0.872822  , 0.67155784, 0.68239547, 0.28970897,
       0.03197737, 0.70100277, 0.45490846, 0.39231366, 0.11513733,
       0.76715532, 0.78973981, 0.67140401, 0.50161316, 0.43302038,
       0.79758311, 0.39199134, 0.88496786, 0.53320005, 0.46280255,
       0.48881804, 0.36267872, 0.15588599, 0.1655232 , 0.7914723 ,
       0.29691104, 0.65190977, 0.14277847, 0.29258485, 0.82965288,
       0.77617088, 0.64542142, 0.83522534, 0.6907077 , 0.49638292,
       0.51558517, 0.0125591 , 0.294341  , 0.57299612, 0.09340377,
       0.83719444, 0.10671193, 0.82604438, 0.41185751, 0.59958

In [138]:
b

array([-0.29311182, -0.50450294, -0.26613373,  1.04646617, -0.191507  ,
        0.65731259,  0.42965426,  0.7885734 ,  1.35204586, -0.5145825 ,
        0.88832721,  0.19686382, -1.78313062, -0.03439583,  3.19508695,
        0.99762407,  0.37460459,  0.21811473, -0.84147167, -0.59775867,
        0.08943513, -1.28466554, -1.36134913, -0.7315272 , -1.34535043,
        1.70384479,  1.57650001, -0.83527353, -1.6590472 ,  0.53000231,
       -0.66811042,  1.56553909,  1.50918453, -2.1820119 ,  0.04845645,
       -1.09778211,  0.64941677,  0.06157541,  0.96767843,  0.49600785,
       -0.01916857,  0.45074768, -0.87917876, -0.54838698,  0.45714307,
        0.33669618, -0.36906356,  1.71474313, -1.15506105, -0.44385509,
        0.14157101,  1.95757356,  1.0605004 , -2.32015662,  2.46757057,
        0.31286818,  0.72821572, -1.07657788, -0.93792464, -0.29660383,
        2.00691308, -0.15747967,  1.28767325,  0.99143665, -0.47783252,
       -0.47137369,  0.61169037, -0.28409213,  1.60079557, -0.45

In [139]:
describe(a)

DescribeResult(nobs=100, minmax=(0.012317895359915454, 0.975080592683623), mean=0.4805143524623178, variance=0.07838907663525384, skewness=-0.13240437447617653, kurtosis=-1.1918441360547365)

In [140]:
describe(b)

DescribeResult(nobs=100, minmax=(-2.320156615292624, 3.195086947692569), mean=0.10284338301914701, variance=1.143006919768311, skewness=0.2692356369978745, kurtosis=-0.19638666764933754)

In [149]:
np.random.seed(1)
np.random.randint(0, 100, 10)

array([37, 12, 72,  9, 75,  5, 79, 64, 16,  1])

In [150]:
x = np.array([1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 4, 5])

In [151]:
x

array([1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 4, 5])

In [152]:
np.unique(x)

array([1, 2, 3, 4, 5])

In [153]:
index, count = np.unique(x, return_counts=True)

In [154]:
index

array([1, 2, 3, 4, 5])

In [155]:
count

array([8, 6, 1, 1, 1], dtype=int64)